# fly.toml app configuration file generated for fly-pgvector on 2024-06-18T07:01:46+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "media-vector-db"
primary_region = "ord"

[build]

[mounts]
  source = "pg_data"
  destination = "/data"

[[services]]
  internal_port = 5432
  protocol = "tcp"
  autostart = true
  auto_stop_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[services.ports]]
    port = 5432
    handlers = ["pg_tls"]

